export const ALL_COMMODITIES: string[] = [
  // --- Cereals & Millets (18) ---
  "Maize",
  "Wheat",
  "Paddy(Dhan)(Common)",
  "Paddy(Dhan)(Basmati)",
  "Rice",
  "Bajra(Pearl Millet/Cumbu)",
  "Jowar(Sorghum)",
  "Barley (Jau)",
  "Ragi (Finger Millet)",
  "Oats",
  "Kodo Millet(Varagu)",
  "Foxtail Millet(Navane)",
  "Little Millet(Samai)",
  "Barnyard Millet(Kuthiraivally)",
  "Proso Millet(Cheena)",
  "Buckwheat",
  "Rye",
  "Sorghum",

  // --- Pulses & Legumes (24) ---
  "Arhar (Tur/Red Gram)(Whole)",
  "Arhar Dal(Tur Dal)",
  "Bengal Gram(Gram)(Whole)",
  "Bengal Gram Dal (Chana Dal)",
  "Green Gram (Moong)(Whole)",
  "Green Gram Dal (Moong Dal)",
  "Black Gram (Urd Bean)(Whole)",
  "Black Gram Dal (Urd Dal)",
  "Masur Dal",
  "Lentil (Masur)(Whole)",
  "Cowpea (Lobia/Karamani)",
  "Field Pea",
  "Peas(Dry)",
  "Peas Wet",
  "Peas cod",
  "Horse Gram(Kulthi)",
  "Moth Dal",
  "Kulthi(Horse Gram)",
  "Rajma",
  "Soyabean",
  "Kabuli Chana(Chickpeas-White)",
  "Gram Raw(Chana)",
  "Dry Peas",
  "White Peas",

  // --- Oilseeds & Commercial (20) ---
  "Groundnut",
  "Groundnut (Split)",
  "Groundnut pods (raw)",
  "Mustard",
  "Mustard Oil",
  "Sunflower",
  "Sunflower Seed",
  "Sesamum(Sesame,Gingelly,Til)",
  "Castor Seed",
  "Cotton",
  "Cotton Seed",
  "Sugarcane",
  "Gur(Jaggery)",
  "Sugar",
  "Jute",
  "Safflower",
  "Linseed",
  "Niger Seed (Ramtil)",
  "Guar",
  "Guar Seed(Cluster Beans)",

  // --- Plantation, Nuts & Cash Crops (12) ---
  "Copra",
  "Coconut",
  "Coconut Oil",
  "Arecanut(Betelnut/Supari)",
  "Tobacco",
  "Sunnhemp",
  "Tea",
  "Coffee",
  "Rubber",
  "Betel Leaves",
  "Cashewnuts",
  "Cashew Nut Raw",

  // --- Vegetables (62) ---
  "Potato",
  "Onion",
  "Onion Green",
  "Tomato",
  "Brinjal",
  "Cabbage",
  "Cauliflower",
  "Bhindi(Ladies Finger)",
  "Bottle gourd",
  "Bitter gourd",
  "Ridgeguard(Tori)",
  "Sponge gourd",
  "Snakeguard",
  "Ashgourd",
  "Pumpkin",
  "Cucumbar(Cucumber)",
  "Carrot",
  "Raddish",
  "Beetroot",
  "Capsicum",
  "Green Chilli",
  "Pointed gourd (Parval)",
  "Little gourd (Kundru)",
  "Tinda",
  "Spinach",
  "Methi(Leaves)",
  "Corriander(Leaves)",
  "Curry Leaves",
  "Mint(Pudina)",
  "Leafy Vegetable",
  "Yam (Ratalu)",
  "Elephant Yam (Suran)",
  "Colocasia",
  "Sweet Potato",
  "Drumstick",
  "Beans",
  "French Beans (Frasbean)",
  "Cluster Beans",
  "Broad Beans",
  "Flat Beans",
  "Broccoli",
  "Zucchini",
  "Mushroom",
  "Knool Khol",
  "Turnip",
  "Chow Chow",
  "Green Banana",
  "Green Papaya",
  "Tapioca",
  "Amaranthus",
  "Lettuce",
  "Celery",
  "Gourds",
  "Ivy Gourd",
  "Round Gourd",
  "Water Chestnut",
  "Raw Mango",
  "Chilli Capsicum",
  "Capsicum (Yellow)",
  "Capsicum (Red)",
  "Ginger(Green)",
  "Garlic",

  // --- Fruits (48) ---
  "Banana",
  "Banana - Green",
  "Apple",
  "Orange",
  "Kinnow",
  "Mousambi(Sweet Lime)",
  "Lemon",
  "Papaya",
  "Papaya (Raw)",
  "Guava",
  "Pomegranate",
  "Chikoos(Sapota)",
  "Grapes",
  "Water Melon",
  "Karbuja(Musk Melon)",
  "Pineapple",
  "Jack Fruit",
  "Custard Apple (Sharifa)",
  "Fig(Anjeer)",
  "Strawberry",
  "Litchi",
  "Plum",
  "Peach",
  "Pear(Marasebu)",
  "Cherry",
  "Apricot(Jardalu/Khumani)",
  "Kiwi Fruit",
  "Dragon Fruit",
  "Avocado",
  "Wood Apple",
  "Amla(Nelli Kai)",
  "Ber(Zizyphus/Borehannu)",
  "Jamun(Narale Hannu)",
  "Tamarind Fruit",
  "Dates",
  "Mulberry",
  "Passion Fruit",
  "Mango (Raw-Ripe)",
  "Mango",
  "Mosambi",
  "Sweet Orange",
  "Grapefruit",
  "Blueberry",
  "Blackberry",
  "Rambutan",
  "Mangosteen",
  "Starfruit",
  "Persimmon",

  // --- Spices & Herbs (28) ---
  "Ginger(Fresh)",
  "Ginger(Dry)",
  "Turmeric",
  "Turmeric (raw)",
  "Dry Chillies",
  "Corriander seed",
  "Cummin Seed(Jeera)",
  "Soanf",
  "Ajwan",
  "Suva (Dill Seed)",
  "Methi(Seeds)",
  "Cardamoms",
  "Large Cardamom",
  "Black Pepper",
  "Cloves",
  "Cinnamon(Dalchini)",
  "Nutmeg",
  "Mace",
  "Star Anise",
  "Asafoetida",
  "Bay Leaf",
  "Poppy Seeds(Khas Khas)",
  "Kalonji",
  "Mustard (Rai)",
  "Saffron",
  "Kokum",
  "Tamarind Seed",
  "Isabgul (Psyllium)",

  // --- Flowers & Dry Fruits (16) ---
  "Rose(Loose)",
  "Rose(Local)",
  "Marigold(Loose)",
  "Marigold(Calcutta)",
  "Jasmine",
  "Chrysanthemum(Loose)",
  "Tuberose(Loose)",
  "Gladiolus Cut Flower",
  "Gerbera",
  "Carnation",
  "Orchid",
  "Lotus",
  "Almond(Badam)",
  "Walnut",
  "Pistachio",
  "Raisins"
];